#!/usr/bin/env python3

from cloxsom.db import DB
from cloxsom.skrap import TestSkrap


def main():
    db = DB()
    db.create_tables()

    o = TestSkrap("testobject", "tester")
    id = db.save_skrap(o)
    print(id)


if __name__ == '__main__':
    main()
