#!/usr/bin/env python3
"""Generate static blog from article files using the closxom plugin system."""

import sys

from closxom.app.genblog import run

if __name__ == '__main__':
    sys.exit(run(sys.argv[1:]))
